
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongock

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

mongock:
  change-logs-scan-package:
    - com.example.mongock.changelogs
  lock-acquired-for-minutes: 5
server:
  port: 8081
